### ISSUE TITLE
System.Xml.XmlException

### ISSUE THREAD

**Issue by BeanBagKing** [BeanBagKing/EventFinder2#5]
**UPDATE - Anyone receiving these errors. I'm currently aware of 0x01, 0x03, and 0x05 causing these issues. If your report contains different hex values, differs drastically in StackTrace, or you think you might have a solution, please report this. Otherwise, I'm not sure there's a need to report every one.** 1 APR 2019

-----------------------------------------------------------------------------
Issue Submission: https://github.com/BeanBagKing/EventFinder2/issues
Date : 3/12/2019 10:48:26 AM
Log : Microsoft-Windows-Partition/Diagnostic
Admin Status: True

System.Xml.XmlException
Message : '', hexadecimal value 0x03, is an invalid character. Line 1, position 1113.
StackTrace :    at System.Xml.XmlTextReaderImpl.Throw(Exception e)
   at System.Xml.XmlTextReaderImpl.Throw(String res, String[] args)
   at System.Xml.XmlTextReaderImpl.ParseText(Int32& startPos, Int32& endPos, Int32& outOrChars)
   at System.Xml.XmlTextReaderImpl.ParseText()
   at System.Xml.XmlTextReaderImpl.ParseElementContent()
   at System.Xml.XmlTextReaderImpl.Read()
   at System.Xml.Linq.XContainer.ReadContentFrom(XmlReader r)
   at System.Xml.Linq.XContainer.ReadContentFrom(XmlReader r, LoadOptions o)
   at System.Xml.Linq.XDocument.Load(XmlReader reader, LoadOptions options)
   at System.Xml.Linq.XDocument.Parse(String text, LoadOptions options)
   at System.Xml.Linq.XDocument.Parse(String text)
   at EventFinder.FindEvents.FindEventsButton_Click(Object sender, EventArgs e)
Data : System.Collections.ListDictionaryInternal
HelpLink : 
HResult : -2146232000
InnerException : 
Source : System.Xml
TargetSite : Void Throw(System.Exception)

**Comment by BeanBagKing** [comment]
I've seen this occur in several logs, with several hex values (0x01 as well). Need to figure out how to properly wrap the events to prevent this.

**Comment by alikat500** [comment]
> 
> 
> Issue Submission: https://github.com/BeanBagKing/EventFinder2/issues
> Date : 3/12/2019 10:48:26 AM
> Log : Microsoft-Windows-Partition/Diagnostic
> Admin Status: True
> 
> System.Xml.XmlException
> Message : '�', hexadecimal value 0x03, is an invalid character. Line 1, position 1113.
> StackTrace : at System.Xml.XmlTextReaderImpl.Throw(Exception e)
> at System.Xml.XmlTextReaderImpl.Throw(String res, String[] args)
> at System.Xml.XmlTextReaderImpl.ParseText(Int32& startPos, Int32& endPos, Int32& outOrChars)
> at System.Xml.XmlTextReaderImpl.ParseText()
> at System.Xml.XmlTextReaderImpl.ParseElementContent()
> at System.Xml.XmlTextReaderImpl.Read()
> at System.Xml.Linq.XContainer.ReadContentFrom(XmlReader r)
> at System.Xml.Linq.XContainer.ReadContentFrom(XmlReader r, LoadOptions o)
> at System.Xml.Linq.XDocument.Load(XmlReader reader, LoadOptions options)
> at System.Xml.Linq.XDocument.Parse(String text, LoadOptions options)
> at System.Xml.Linq.XDocument.Parse(String text)
> at EventFinder.FindEvents.FindEventsButton_Click(Object sender, EventArgs e)
> Data : System.Collections.ListDictionaryInternal
> HelpLink :
> HResult : -2146232000
> InnerException :
> Source : System.Xml
> TargetSite : Void Throw(System.Exception)

Hi,

Not sure if you still need error logs. But, I received a similar message:

Issue Submission: https://github.com/BeanBagKing/EventFinder2/issues
Date : 4/1/2019 07:40:16
Log : Microsoft-Windows-Sysmon/Operational
Admin Status: True

System.Xml.XmlException
Message : '', hexadecimal value 0x05, is an invalid character. Line 1, position 844.
StackTrace :    at System.Xml.XmlTextReaderImpl.Throw(Exception e)
   at System.Xml.XmlTextReaderImpl.Throw(String res, String[] args)
   at System.Xml.XmlTextReaderImpl.ParseText(Int32& startPos, Int32& endPos, Int32& outOrChars)
   at System.Xml.XmlTextReaderImpl.ParseText()
   at System.Xml.XmlTextReaderImpl.ParseElementContent()
   at System.Xml.XmlTextReaderImpl.Read()
   at System.Xml.Linq.XContainer.ReadContentFrom(XmlReader r)
   at System.Xml.Linq.XContainer.ReadContentFrom(XmlReader r, LoadOptions o)
   at System.Xml.Linq.XDocument.Load(XmlReader reader, LoadOptions options)
   at System.Xml.Linq.XDocument.Parse(String text, LoadOptions options)
   at System.Xml.Linq.XDocument.Parse(String text)
   at EventFinder.FindEvents.FindEventsButton_Click(Object sender, EventArgs e)
Data : System.Collections.ListDictionaryInternal
HelpLink : 
HResult : -2146232000
InnerException : 
Source : System.Xml
TargetSite : Void Throw(System.Exception)

**Comment by BeanBagKing** [comment]
Thanks, I hadn't seen the hex 0x05 yet, so this will be helpful when/if I can figure out a solution for these (I'm sure there's a whole group of hex values, probably listed somewhere on StackOverflow). In the mean time, if you are analyzing anything important, just be aware that you may have missed something in (or that entire) log.
